// Packs the Next.js standalone build into a folder the host can run without compiling anything.
// Usage: node scripts/assemble-deploy.mjs <outDir>   (after `npm run build`)
import { cpSync, existsSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const out = process.argv[2] || "dist-deploy";
const root = process.cwd();
if (!existsSync(join(root, ".next/standalone/server.js"))) {
  console.error("Run `npm run build` first (output: 'standalone' must be enabled).");
  process.exit(1);
}

rmSync(out, { recursive: true, force: true });
// Everything runnable lives in <out>/app (with its own node_modules). A root-level `npm install`
// only manages <out>/node_modules, so it can never prune the bundled packages.
const app = join(out, "app");
// The traced node_modules are shipped too, so the host needs no `npm install` and never sees a
// `next` dependency (some hosts then force their own `next build`, which can't run there).
// sharp / @img are skipped: images are served unoptimized, so they are never loaded.
const SKIP = ["sharp", "@img"].map((m) => join(".next/standalone", "node_modules", m));
cpSync(join(root, ".next/standalone"), app, {
  recursive: true,
  filter: (src) => !SKIP.some((m) => src.includes(m)),
});
cpSync(join(root, ".next/static"), join(app, ".next/static"), { recursive: true });
cpSync(join(root, "public"), join(app, "public"), { recursive: true });

const pkg = {
  name: "basst-cut-server",
  version: "1.0.0",
  private: true,
  description: "Prebuilt BASST CUT app, generated by GitHub Actions from the main branch. Do not edit here.",
  main: "server.js",
  scripts: {
    // Nothing is compiled on the host. "build" only lays the prebuilt app out at the top level
    // (.next, server.js, public, node_modules) because the host checks for a .next output folder.
    build: "node place-app.mjs",
    start: "node server.js",
  },
  engines: { node: ">=20.9" },
  dependencies: {},
};
writeFileSync(join(out, "package.json"), JSON.stringify(pkg, null, 2) + "\n");
writeFileSync(join(out, ".gitignore"), ".env\n");
writeFileSync(
  join(out, "place-app.mjs"),
  `// Lays out the prebuilt app (from ./app) the way \`next build\` with output: "standalone" would,
// after the host's npm install. Nothing is compiled here.
//   ./.next/standalone/server.js  ← what Next.js-aware hosts look for
//   ./server.js, ./.next, ./public, ./node_modules  ← so \`npm start\` works from the root too
import { cpSync, readdirSync } from "node:fs";
for (const entry of readdirSync("app")) {
  if (entry === "package.json") continue;
  cpSync(\`app/\${entry}\`, entry, { recursive: true, force: true });
}
cpSync("app", ".next/standalone", { recursive: true, force: true });
console.log("Prebuilt BASST CUT app ready (built by GitHub Actions): .next/standalone/server.js");
`
);
writeFileSync(
  join(out, "README.md"),
  `# BASST CUT — deploy branch\n\nGenerated automatically from \`main\` by GitHub Actions. Do not edit.\n\nPlain Node.js app: no install or build needed. \`npm run build\` copies app/ to the root (no compiling); \`npm start\` runs \`node server.js\`.\n`
);
console.log(`Prebuilt app written to ${out}/`);
