// Packs the Next.js standalone build into a folder the host can run without compiling anything.
// Usage: node scripts/assemble-deploy.mjs <outDir>   (after `npm run build`)
import { cpSync, existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const out = process.argv[2] || "dist-deploy";
const root = process.cwd();
if (!existsSync(join(root, ".next/standalone/server.js"))) {
  console.error("Run `npm run build` first (output: 'standalone' must be enabled).");
  process.exit(1);
}

rmSync(out, { recursive: true, force: true });
cpSync(join(root, ".next/standalone"), out, {
  recursive: true,
  filter: (src) => !src.includes(`${join(".next/standalone", "node_modules")}`),
});
cpSync(join(root, ".next/static"), join(out, ".next/static"), { recursive: true });
cpSync(join(root, "public"), join(out, "public"), { recursive: true });

const version = (name) => JSON.parse(readFileSync(join(root, "node_modules", name, "package.json"), "utf8")).version;
const pkg = {
  name: "basst-cut-deploy",
  version: "1.0.0",
  private: true,
  description: "Prebuilt BASST CUT app, generated by GitHub Actions from the main branch. Do not edit here.",
  scripts: {
    build: 'echo "Prebuilt by GitHub Actions - nothing to build"',
    start: "node server.js",
  },
  engines: { node: ">=20.9" },
  dependencies: Object.fromEntries(["next", "react", "react-dom", "mysql2"].map((n) => [n, version(n)])),
};
writeFileSync(join(out, "package.json"), JSON.stringify(pkg, null, 2) + "\n");
writeFileSync(join(out, ".gitignore"), "node_modules\n.env\n");
writeFileSync(
  join(out, "README.md"),
  `# BASST CUT — deploy branch\n\nGenerated automatically from \`main\` by GitHub Actions. Do not edit.\n\nHost settings: build \`npm run build\` (no-op), start \`npm start\` (\`node server.js\`).\n`
);
console.log(`Prebuilt app written to ${out}/`);
